server:
  port: {$SPRING_SERVER_PORT}
app:
  storage:
    source-dir: /media/source
    processed-dir: /media/processed
    thumbnail-dir: /media/thumbnails

spring:
  datasource:
    url: jdbc:h2:file:/media/database/videodb
    driverClassName: org.h2.Driver
    username: {$H2_USERNAME}
    password: {$H2_PASSWORD}

  jpa:
    database-platform: org.h2.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true